kind: Namespace
apiVersion: v1
metadata:
  name: api
  labels:
    name: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-terraform-registry
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
        app: "simple-terraform-registry"
        ver: "1"
        env: "prod"
  template:
    metadata:
      labels:
        app: "simple-terraform-registry"
        ver: "1"
        env: "prod"
    spec:
      containers:
      - name: simple-terraform-registry
        image: gabrielmccoll/simple-terraform-registry:0.0.4
        ports:
        - name:  http
          containerPort:  80
          protocol: TCP
        resources:
          requests:
            cpu: "300m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /.well-known/terraform.json
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /.well-known/terraform.json
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: simple-terraform-registry
  namespace: api
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
  selector:
        app: "simple-terraform-registry"
        ver: "1"
        env: "prod"

